# Generated by Django 4.0.4 on 2022-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_number',
            field=models.IntegerField(default=0),
        ),
    ]
