# Generated by Django 4.0.4 on 2022-05-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaldocument',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('In progress', 'In progress'), ('Expired', 'Expired')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
