# Generated by Django 4.0.4 on 2022-05-27 14:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.IntegerField(default=main.models.random_car_number, unique=True),
        ),
    ]
