# Generated by Django 4.0.4 on 2022-05-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_car_car_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalDocument',
            new_name='Document',
        ),
    ]
