# Generated by Django 4.0.4 on 2022-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_document_rent_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rent_date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='rent_date_to',
            field=models.DateTimeField(),
        ),
    ]
