# Generated by Django 4.0.4 on 2022-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_document_rent_date_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='client_f_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='client_l_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='company_title',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='rent_date_from',
            new_name='renting_date_from',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='rent_date_to',
            new_name='renting_date_to',
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('In progress', 'In progress'), ('Expired', 'Expired')], default='In progress', max_length=255),
        ),
    ]
